### ISSUE TITLE
Improve Thruster Server struct performance

### ISSUE THREAD

**Issue by trezm** [thruster-rs/Thruster#120]
Would love to get the home-grown implementation of an http encoder/decoder more in line with hyper's perf. 

For perf focused users, you can now easily use Hyper as the backend, but it would be nice to be on level playing fields in the future.

**Comment by Austaras** [comment]
No idea why, but in my machines thruster's own server is around 50% faster than using hyper

**Comment by trezm** [comment]
That's fascinating! Are you running in release? I wonder if we're using some non-performant hyper method calls. You're just using the "out of the box" Hyper server and Thruster server, correct?

**Comment by Austaras** [comment]
Well, it seems likely to be later case. I ran basic and hyper example in this repo both in release, and got 300k/220k rps

**Comment by trezm** [comment]
Very interesting, I'll have to do some testing to dig into why. The homegrown server should be faster, but not by that big a margin!

**Comment by trezm** [comment]
@Austaras, would you mind sharing the command you're using to benchmark each? I get much more comparable results between the thruster and hyper backends:

Thruster: 3316177 requests in 30.10s
Hyper: 3071149 requests in 30.10s

If you're on a Macbook Pro, it might be getting thermally throttled if you run the compiles in series.

**Comment by Austaras** [comment]
Just a simple `wrk`. So I'm using a quite powerful desktop on Linux(I got around 3x rps to your result) and only test for 10 seconds, maybe these will effect the result.
