### ISSUE TITLE
No readme on crates.io

### ISSUE THREAD

**Issue by yerke** [thruster-rs/Thruster#181]
Thanks for working on this project.

If you check https://crates.io/crates/thruster it says `thruster v1.1.2 appears to have no README.md file`.
Not sure if you have noticed it before.

**Comment by trezm** [comment]
I hadn't! I'll fix this, I wonder if this is because the readme is in the
root? I'll put a fix our tomorrow morning!

**Comment by trezm** [comment]
Looks like it's all set now!
