### ISSUE TITLE
Alias ideas

### ISSUE THREAD

**Issue by ynuwenhof** [thruster-rs/Thruster#209]
Hey,

Here's a small collection of alias ideas that I find to be fitting.

Ordered from best to worst, IMO.

[use_sub_app](https://docs.rs/thruster/1.1.14/thruster/struct.App.html#method.use_sub_app)

- `nest`
- `app`
- `sub`

[use_middleware](https://docs.rs/thruster/1.1.14/thruster/struct.App.html#method.use_middleware)
- `middleware`
- `with`
- `mid`

I might come up with some more alias ideas soon 👍

**Comment by trezm** [comment]
I like your top choice for both of those! I struggle to remember my original logic around choosing the existing names, but I think these options are really nice and succinct.

**Comment by Israel-Laguan** [comment]
What about `router` or similar for subapp?

**Comment by trezm** [comment]
I think that's a reasonable alias! Subapp has always felt a little...
Poorly named to me? I'll put up a PR with the alias this afternoon.

**Comment by Israel-Laguan** [comment]
Also, `router` is the usual name in other languages and libraries. 

BTW, great work for this library, our team is leveraging it to try it above other ones!

**Comment by trezm** [comment]
Should be resolved by https://github.com/thruster-rs/Thruster/pull/222, will put out a new release soon!

**Comment by trezm** [comment]
Should now be available in release 1.2.5! https://github.com/thruster-rs/Thruster/pull/223
