### ISSUE TITLE
[Feature] Create an example for handling sockets and socket messages (Websockets)

### ISSUE THREAD

**Issue by trezm** [thruster-rs/Thruster#21]
While using the hyper server, this should already be possible. This is the tracking issue to make that support first class, along with an example and short guide.

Ideally the upgrade for the socket will be handled via a single middleware function, but we should consider the following:

- [ ] Should each socket be stored in a static map somewhere for reference later?
- [ ] Should we also have first class support for socket.io?

**Comment by dns2utf8** [comment]
Is this a tracking issue for WebSocket?

**Comment by trezm** [comment]
Yes! It will be. Expect some updates soon. I'm currently working on
stabilizing the builtin hyper contexts a little and will move on to
websockets (also based on hyper,) from there.
