### ISSUE TITLE
How to set CORS with thruster?

### ISSUE THREAD

**Issue by CHCP** [thruster-rs/Thruster#215]
Hi @trezm 
    I run a thruster-socketio server, need to set some special domains, but I didn't find any examples to show how to set CORS. May I know how to set CORS with Thruster?  

Thanks a lot.

```
    use thruster::middleware::cors::cors;
    ...
    app.use_middleware("/", async_middleware!(Ctx, [cors]));
    ...
```

**Comment by trezm** [comment]
That looks like it should work, does it not?

This CORS opens up everything though, the code for a more specific one is pretty simple if you'd like to update it:

```rs
#[middleware_fn]
pub async fn cors<T: 'static + Context + Send>(
    mut context: T,
    next: MiddlewareNext<T>,
) -> MiddlewareResult<T> {
    context.set("Access-Control-Allow-Origin", "*");
    context.set("Access-Control-Allow-Headers", "*");
    context.set(
        "Access-Control-Allow-Methods",
        "GET, POST, PUT, DELETE, OPTIONS",
    );

    next(context).await
}
```

You'd adjust the fields as necessary.

**Comment by CHCP** [comment]
Thanks @trezm 
I update the code a little follow as yours, but it did not work. I can still access mydomain.com from other address, like wss://bridge.otherdomain.com.

```
#[middleware_fn]
async fn cors(mut context: Ctx, next: MiddlewareNext<Ctx>) -> MiddlewareResult<Ctx> {
    context.set("Access-Control-Allow-Origin", "wss://bridge.mydomain.com");
    context.set("Access-Control-Allow-Headers", "*");
    context.set(
        "Access-Control-Allow-Methods",
        "GET, POST, PUT, DELETE, OPTIONS",
    );

    next(context).await
}
```

**Comment by CHCP** [comment]
I add some conditions, and test with https://bridge.mydomain.com, but it is still did not work.

```
    context.set("Access-Control-Allow-Credentials", "true");
```

**Comment by CHCP** [comment]
I set the allow-origin to "https://bridge.mydomain.com", so if someone access from other domain, the access will be refused, is this correct? But I found that still can access this domain from other domains.

The curl response as follows:
```
$ curl -v http://localhost:3101/plaintext
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying ::1:3101...
*   Trying 127.0.0.1:3101...
* Connected to localhost (127.0.0.1) port 3101 (#0)
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0> GET /plaintext HTTP/1.1
> Host: localhost:3101
> User-Agent: curl/7.73.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< server: thruster
< access-control-allow-origin: https://bridge.mydomain.com
< access-control-allow-headers: *
< access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS
< access-control-allow-credentials: true
< content-length: 2218
< date: Fri, 25 Mar 2022 22:30:40 GMT
<
{ [2218 bytes data]
100  2218  100  2218    0     0   9728      0 --:--:-- --:--:-- --:--:--  9728<!doctype html>
<html>
  <head>
    <title>Socket.IO chat</title>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font: 13px Helvetica, Arial; }
   ...

```

**Comment by trezm** [comment]
That looks correct to me, the initial page load should work, but any calls
made by the page at localhost should fail. Are you seeing a fetch request
on the page go through successfully as well?

**Comment by CHCP** [comment]
yes, I can access the page from localhost,  and can connect with web socket, receive data.

**Comment by CHCP** [comment]
May I know how this going? Thanks

**Comment by CHCP** [comment]
@trezm  
 Thanks a lot, I will study your code and sync my status.

**Comment by CHCP** [comment]
Hi @trezm 
  My program use thruster as web socket server, maybe this issue should be moved to [thruster-socketio](https://github.com/thruster-rs/thruster-socketio) repo.
  My code as follows, almost reference [thruster-socketio example](https://github.com/thruster-rs/thruster-socketio/blob/master/socketio_middleware/examples/chat.rs), I'm not sure whether this usage of CORS is correct?  Would you please to give me some advices? Thank you.

```
//use extern crates and path
use log::{trace, debug, info};
use hyper::Body;

use thruster::context::basic_hyper_context::{generate_context, BasicHyperContext as Ctx};
use thruster::context::hyper_request::HyperRequest;
use thruster::hyper_server::HyperServer;
use thruster::Context;
//use thruster::middleware::cors::cors;
use thruster::middleware::file::get_file;
use thruster::{async_middleware, middleware_fn};
use thruster::{App, ThrusterServer};
use thruster::{MiddlewareNext, MiddlewareResult};

#[middleware_fn]
async fn cors(mut context: Ctx, next: MiddlewareNext<Ctx>) -> MiddlewareResult<Ctx> {
    context.set("Access-Control-Allow-Origin", "https://bridge.mydomain.com");
    context.set("Access-Control-Allow-Headers", "*");
    context.set(
        "Access-Control-Allow-Methods",
        "GET, POST, PUT, DELETE, OPTIONS",
    );
    context.set("Access-Control-Allow-Credentials", "true");

    next(context).await
}

#[middleware_fn]
async fn noop(context: Ctx, _next: MiddlewareNext<Ctx>) -> MiddlewareResult<Ctx> {
    Ok(context)
}

#[middleware_fn]
pub async fn io(context: Ctx, _next: MiddlewareNext<Ctx>) -> MiddlewareResult<Ctx> {
    Ok(context)
}

#[middleware_fn]
async fn index(mut context: Ctx, _next: MiddlewareNext<Ctx>) -> MiddlewareResult<Ctx> {
    let content = get_file("test/chat.html").unwrap();
    context.body = Body::from(content);

    Ok(context)
}

#[tokio::main]
async fn main() {
    let host = "0.0.0.0".to_string();
    let port = "3101".to_string();
    info!("Socketio listening on: {}:{}", host, port);

    let mut app = App::<HyperRequest, Ctx, ()>::create(generate_context, ());
    app.use_middleware("/", async_middleware!(Ctx, [cors]));
    app.get("/socket.io/*", async_middleware!(Ctx, [io]));
    app.get("/", async_middleware!(Ctx, [index]));
    app.options("/socket.io/*", async_middleware!(Ctx, [noop]));
    let _ = HyperServer::new(app)
        .with_upgrades(true)
        .build(&host, port.parse::<u16>().unwrap())
        .await;
}
```

**Comment by CHCP** [comment]
Hi @trezm 
  I gave an example for CORS, but I can still access the web sockets from any web site like ```localhost:3031```,  would you like to gave me any advices? Thank you very much.

**Comment by trezm** [comment]
A few things:
- I'm having trouble finding the exact spec, but CORS does not apply to websockets, see [here](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-6.0#websocket-origin-restriction)
- Since thruster-socketio only supports the `websocket` connection at the moment (not `polling`) that means you'll have to secure it by other means, perhaps using the `origin` header.
- There _is_ an issue that will be difficult to get by without refactoring in the `socketio` middleware, where the middleware dumps any previous headers set on the context. You can get around this pretty easily by flipping when you call `next` to be before setting the headers instead of after, like so:
```rs
#[middleware_fn]
async fn cors(context: Ctx, next: MiddlewareNext<Ctx>) -> MiddlewareResult<Ctx> {
    let mut context = next(context).await?;

    context.set("Access-Control-Allow-Origin", "https://bridge.mydomain.com");
    context.set("Access-Control-Allow-Headers", "*");
    context.set(
        "Access-Control-Allow-Methods",
        "GET, POST, PUT, DELETE, OPTIONS",
    );
    context.set("Access-Control-Allow-Credentials", "true");

    Ok(context)
}
```
Remember though, since you're using websockets, this still won't work for restricting CORS since browsers don't respect those headers for websockets.

**Comment by CHCP** [comment]
Got it, and thanks for your kind advices, I will find some restricts in Front-end.
